/** Segmentos padrão de mercado (baseados nas seções CNAE/IBGE), usados no CRM. */

export const CRM_SEGMENTS = [
  "Agronegócio, agricultura e pecuária",
  "Alimentos e bebidas",
  "Automotivo e mobilidade",
  "Bens de consumo e varejo",
  "Comércio atacadista e distribuição",
  "Construção civil e infraestrutura",
  "Educação e treinamento",
  "Energia, petróleo e gás",
  "Farmacêutico e ciências da vida",
  "Financeiro, bancos e seguros",
  "Governo e setor público",
  "Imobiliário",
  "Indústria química e petroquímica",
  "Indústria de transformação e manufatura",
  "Logística, transporte e armazenagem",
  "Mineração e metalurgia",
  "Mídia, comunicação e entretenimento",
  "Papel, celulose e embalagens",
  "Saúde e hospitais",
  "Serviços profissionais e consultoria",
  "Siderurgia e bens de capital",
  "Tecnologia da informação e software",
  "Telecomunicações",
  "Terceiro setor e ONGs",
  "Têxtil, moda e calçados",
  "Turismo, hotelaria e eventos",
  "Utilidades públicas (água, saneamento e resíduos)",
  "Outros",
] as const;

/** Áreas/departamentos padrão das empresas, usados no cadastro de pessoas do CRM. */
export const CRM_DEPARTMENTS = [
  "Presidência / Diretoria Executiva",
  "Administrativo",
  "Comercial / Vendas",
  "Marketing",
  "Financeiro",
  "Contabilidade",
  "Controladoria",
  "Compras / Suprimentos",
  "Jurídico",
  "Recursos Humanos / Gente e Gestão",
  "Operações",
  "Produção / Manufatura",
  "Qualidade",
  "Manutenção",
  "Logística / Supply Chain",
  "Engenharia",
  "Pesquisa e Desenvolvimento / Inovação",
  "Tecnologia da Informação",
  "Projetos / PMO",
  "Planejamento Estratégico",
  "Segurança do Trabalho / SESMT",
  "Meio Ambiente / ESG / Sustentabilidade",
  "Atendimento ao Cliente / SAC",
  "Comércio Exterior",
  "Comunicação / Relações Institucionais",
  "Outros",
] as const;
