/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrasilRouteImport } from './routes/brasil'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContentRouteImport } from './routes/content'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AboutSlugRouteImport } from './routes/about_.$slug'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminBrasilRouteImport } from './routes/admin.brasil'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminTextsRouteImport } from './routes/admin.texts'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as BrasilSlugRouteImport } from './routes/brasil_.$slug'
import { Route as ContentSlugRouteImport } from './routes/content.$slug'
import { Route as NewsletterUnsubscribeRouteImport } from './routes/newsletter.unsubscribe'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrasilRoute = BrasilRouteImport.update({
  id: '/brasil',
  path: '/brasil',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSlugRoute = AboutSlugRouteImport.update({
  id: '/about_/$slug',
  path: '/about/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrasilRoute = AdminBrasilRouteImport.update({
  id: '/admin/brasil',
  path: '/admin/brasil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/admin/hero',
  path: '/admin/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/admin/newsletter',
  path: '/admin/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTextsRoute = AdminTextsRouteImport.update({
  id: '/admin/texts',
  path: '/admin/texts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/admin/theme',
  path: '/admin/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const BrasilSlugRoute = BrasilSlugRouteImport.update({
  id: '/brasil_/$slug',
  path: '/brasil/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentSlugRoute = ContentSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ContentRoute,
} as any)
const NewsletterUnsubscribeRoute = NewsletterUnsubscribeRouteImport.update({
  id: '/newsletter/unsubscribe',
  path: '/newsletter/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brasil': typeof BrasilRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about/$slug': typeof AboutSlugRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/brasil': typeof AdminBrasilRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/texts': typeof AdminTextsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/brasil/$slug': typeof BrasilSlugRoute
  '/content/$slug': typeof ContentSlugRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brasil': typeof BrasilRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about/$slug': typeof AboutSlugRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/brasil': typeof AdminBrasilRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/texts': typeof AdminTextsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/brasil/$slug': typeof BrasilSlugRoute
  '/content/$slug': typeof ContentSlugRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brasil': typeof BrasilRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about_/$slug': typeof AboutSlugRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/brasil': typeof AdminBrasilRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/texts': typeof AdminTextsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/brasil_/$slug': typeof BrasilSlugRoute
  '/content/$slug': typeof ContentSlugRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brasil'
    | '/careers'
    | '/contact'
    | '/content'
    | '/privacy'
    | '/terms'
    | '/about/$slug'
    | '/admin/applications'
    | '/admin/brasil'
    | '/admin/content'
    | '/admin/hero'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/texts'
    | '/admin/theme'
    | '/brasil/$slug'
    | '/content/$slug'
    | '/newsletter/unsubscribe'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brasil'
    | '/careers'
    | '/contact'
    | '/content'
    | '/privacy'
    | '/terms'
    | '/about/$slug'
    | '/admin/applications'
    | '/admin/brasil'
    | '/admin/content'
    | '/admin/hero'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/texts'
    | '/admin/theme'
    | '/brasil/$slug'
    | '/content/$slug'
    | '/newsletter/unsubscribe'
    | '/services/$slug'
    | '/admin'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brasil'
    | '/careers'
    | '/contact'
    | '/content'
    | '/privacy'
    | '/terms'
    | '/about_/$slug'
    | '/admin/applications'
    | '/admin/brasil'
    | '/admin/content'
    | '/admin/hero'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/texts'
    | '/admin/theme'
    | '/brasil_/$slug'
    | '/content/$slug'
    | '/newsletter/unsubscribe'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrasilRoute: typeof BrasilRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ContentRoute: typeof ContentRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AboutSlugRoute: typeof AboutSlugRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminBrasilRoute: typeof AdminBrasilRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminTextsRoute: typeof AdminTextsRoute
  AdminThemeRoute: typeof AdminThemeRoute
  BrasilSlugRoute: typeof BrasilSlugRoute
  NewsletterUnsubscribeRoute: typeof NewsletterUnsubscribeRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brasil': {
      id: '/brasil'
      path: '/brasil'
      fullPath: '/brasil'
      preLoaderRoute: typeof BrasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/$slug': {
      id: '/about_/$slug'
      path: '/about/$slug'
      fullPath: '/about/$slug'
      preLoaderRoute: typeof AboutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/brasil': {
      id: '/admin/brasil'
      path: '/admin/brasil'
      fullPath: '/admin/brasil'
      preLoaderRoute: typeof AdminBrasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/admin/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/admin/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/texts': {
      id: '/admin/texts'
      path: '/admin/texts'
      fullPath: '/admin/texts'
      preLoaderRoute: typeof AdminTextsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/admin/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brasil_/$slug': {
      id: '/brasil_/$slug'
      path: '/brasil/$slug'
      fullPath: '/brasil/$slug'
      preLoaderRoute: typeof BrasilSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$slug': {
      id: '/content/$slug'
      path: '/$slug'
      fullPath: '/content/$slug'
      preLoaderRoute: typeof ContentSlugRouteImport
      parentRoute: typeof ContentRoute
    }
    '/newsletter/unsubscribe': {
      id: '/newsletter/unsubscribe'
      path: '/newsletter/unsubscribe'
      fullPath: '/newsletter/unsubscribe'
      preLoaderRoute: typeof NewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContentRouteChildren {
  ContentSlugRoute: typeof ContentSlugRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentSlugRoute: ContentSlugRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrasilRoute: BrasilRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ContentRoute: ContentRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AboutSlugRoute: AboutSlugRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminBrasilRoute: AdminBrasilRoute,
  AdminContentRoute: AdminContentRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminTextsRoute: AdminTextsRoute,
  AdminThemeRoute: AdminThemeRoute,
  BrasilSlugRoute: BrasilSlugRoute,
  NewsletterUnsubscribeRoute: NewsletterUnsubscribeRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
