/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrasilRouteImport } from './routes/brasil'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContentRouteImport } from './routes/content'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AboutSlugRouteImport } from './routes/about_.$slug'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminBoletimRouteImport } from './routes/admin.boletim'
import { Route as AdminBrasilRouteImport } from './routes/admin.brasil'
import { Route as AdminConsultoresRouteImport } from './routes/admin.consultores'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminContratoRouteImport } from './routes/admin.contrato'
import { Route as AdminEmpresaRouteImport } from './routes/admin.empresa'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminHistoricoRouteImport } from './routes/admin.historico'
import { Route as AdminIndicadoresRouteImport } from './routes/admin.indicadores'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTextsRouteImport } from './routes/admin.texts'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BoletimCancelarRouteImport } from './routes/boletim.cancelar'
import { Route as BrasilSlugRouteImport } from './routes/brasil_.$slug'
import { Route as ContentSlugRouteImport } from './routes/content.$slug'
import { Route as NewsletterUnsubscribeRouteImport } from './routes/newsletter.unsubscribe'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ApiPublicBulletinWeeklyRouteImport } from './routes/api/public/bulletin-weekly'
import { Route as ApiPublicNewsletterWeeklyRouteImport } from './routes/api/public/newsletter-weekly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrasilRoute = BrasilRouteImport.update({
  id: '/brasil',
  path: '/brasil',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSlugRoute = AboutSlugRouteImport.update({
  id: '/about_/$slug',
  path: '/about/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBoletimRoute = AdminBoletimRouteImport.update({
  id: '/admin/boletim',
  path: '/admin/boletim',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrasilRoute = AdminBrasilRouteImport.update({
  id: '/admin/brasil',
  path: '/admin/brasil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsultoresRoute = AdminConsultoresRouteImport.update({
  id: '/admin/consultores',
  path: '/admin/consultores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContratoRoute = AdminContratoRouteImport.update({
  id: '/admin/contrato',
  path: '/admin/contrato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresaRoute = AdminEmpresaRouteImport.update({
  id: '/admin/empresa',
  path: '/admin/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/admin/hero',
  path: '/admin/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoricoRoute = AdminHistoricoRouteImport.update({
  id: '/admin/historico',
  path: '/admin/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndicadoresRoute = AdminIndicadoresRouteImport.update({
  id: '/admin/indicadores',
  path: '/admin/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/admin/newsletter',
  path: '/admin/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTextsRoute = AdminTextsRouteImport.update({
  id: '/admin/texts',
  path: '/admin/texts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/admin/theme',
  path: '/admin/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BoletimCancelarRoute = BoletimCancelarRouteImport.update({
  id: '/boletim/cancelar',
  path: '/boletim/cancelar',
  getParentRoute: () => rootRouteImport,
} as any)
const BrasilSlugRoute = BrasilSlugRouteImport.update({
  id: '/brasil_/$slug',
  path: '/brasil/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentSlugRoute = ContentSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ContentRoute,
} as any)
const NewsletterUnsubscribeRoute = NewsletterUnsubscribeRouteImport.update({
  id: '/newsletter/unsubscribe',
  path: '/newsletter/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBulletinWeeklyRoute = ApiPublicBulletinWeeklyRouteImport.update({
  id: '/api/public/bulletin-weekly',
  path: '/api/public/bulletin-weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterWeeklyRoute =
  ApiPublicNewsletterWeeklyRouteImport.update({
    id: '/api/public/newsletter-weekly',
    path: '/api/public/newsletter-weekly',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brasil': typeof BrasilRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about/$slug': typeof AboutSlugRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/boletim': typeof AdminBoletimRoute
  '/admin/brasil': typeof AdminBrasilRoute
  '/admin/consultores': typeof AdminConsultoresRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/contrato': typeof AdminContratoRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/texts': typeof AdminTextsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/boletim/cancelar': typeof BoletimCancelarRoute
  '/brasil/$slug': typeof BrasilSlugRoute
  '/content/$slug': typeof ContentSlugRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/public/bulletin-weekly': typeof ApiPublicBulletinWeeklyRoute
  '/api/public/newsletter-weekly': typeof ApiPublicNewsletterWeeklyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brasil': typeof BrasilRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about/$slug': typeof AboutSlugRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/boletim': typeof AdminBoletimRoute
  '/admin/brasil': typeof AdminBrasilRoute
  '/admin/consultores': typeof AdminConsultoresRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/contrato': typeof AdminContratoRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/texts': typeof AdminTextsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/boletim/cancelar': typeof BoletimCancelarRoute
  '/brasil/$slug': typeof BrasilSlugRoute
  '/content/$slug': typeof ContentSlugRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/public/bulletin-weekly': typeof ApiPublicBulletinWeeklyRoute
  '/api/public/newsletter-weekly': typeof ApiPublicNewsletterWeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brasil': typeof BrasilRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about_/$slug': typeof AboutSlugRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/boletim': typeof AdminBoletimRoute
  '/admin/brasil': typeof AdminBrasilRoute
  '/admin/consultores': typeof AdminConsultoresRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/contrato': typeof AdminContratoRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/texts': typeof AdminTextsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/boletim/cancelar': typeof BoletimCancelarRoute
  '/brasil_/$slug': typeof BrasilSlugRoute
  '/content/$slug': typeof ContentSlugRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/public/bulletin-weekly': typeof ApiPublicBulletinWeeklyRoute
  '/api/public/newsletter-weekly': typeof ApiPublicNewsletterWeeklyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brasil'
    | '/careers'
    | '/contact'
    | '/content'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/about/$slug'
    | '/admin/applications'
    | '/admin/approvals'
    | '/admin/boletim'
    | '/admin/brasil'
    | '/admin/consultores'
    | '/admin/content'
    | '/admin/contrato'
    | '/admin/empresa'
    | '/admin/hero'
    | '/admin/historico'
    | '/admin/indicadores'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/texts'
    | '/admin/theme'
    | '/admin/users'
    | '/boletim/cancelar'
    | '/brasil/$slug'
    | '/content/$slug'
    | '/newsletter/unsubscribe'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
    | '/api/public/bulletin-weekly'
    | '/api/public/newsletter-weekly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brasil'
    | '/careers'
    | '/contact'
    | '/content'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/about/$slug'
    | '/admin/applications'
    | '/admin/approvals'
    | '/admin/boletim'
    | '/admin/brasil'
    | '/admin/consultores'
    | '/admin/content'
    | '/admin/contrato'
    | '/admin/empresa'
    | '/admin/hero'
    | '/admin/historico'
    | '/admin/indicadores'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/texts'
    | '/admin/theme'
    | '/admin/users'
    | '/boletim/cancelar'
    | '/brasil/$slug'
    | '/content/$slug'
    | '/newsletter/unsubscribe'
    | '/services/$slug'
    | '/admin'
    | '/services'
    | '/api/public/bulletin-weekly'
    | '/api/public/newsletter-weekly'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brasil'
    | '/careers'
    | '/contact'
    | '/content'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/about_/$slug'
    | '/admin/applications'
    | '/admin/approvals'
    | '/admin/boletim'
    | '/admin/brasil'
    | '/admin/consultores'
    | '/admin/content'
    | '/admin/contrato'
    | '/admin/empresa'
    | '/admin/hero'
    | '/admin/historico'
    | '/admin/indicadores'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/texts'
    | '/admin/theme'
    | '/admin/users'
    | '/boletim/cancelar'
    | '/brasil_/$slug'
    | '/content/$slug'
    | '/newsletter/unsubscribe'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
    | '/api/public/bulletin-weekly'
    | '/api/public/newsletter-weekly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrasilRoute: typeof BrasilRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ContentRoute: typeof ContentRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AboutSlugRoute: typeof AboutSlugRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminBoletimRoute: typeof AdminBoletimRoute
  AdminBrasilRoute: typeof AdminBrasilRoute
  AdminConsultoresRoute: typeof AdminConsultoresRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminContratoRoute: typeof AdminContratoRoute
  AdminEmpresaRoute: typeof AdminEmpresaRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminHistoricoRoute: typeof AdminHistoricoRoute
  AdminIndicadoresRoute: typeof AdminIndicadoresRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTextsRoute: typeof AdminTextsRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminUsersRoute: typeof AdminUsersRoute
  BoletimCancelarRoute: typeof BoletimCancelarRoute
  BrasilSlugRoute: typeof BrasilSlugRoute
  NewsletterUnsubscribeRoute: typeof NewsletterUnsubscribeRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiPublicBulletinWeeklyRoute: typeof ApiPublicBulletinWeeklyRoute
  ApiPublicNewsletterWeeklyRoute: typeof ApiPublicNewsletterWeeklyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brasil': {
      id: '/brasil'
      path: '/brasil'
      fullPath: '/brasil'
      preLoaderRoute: typeof BrasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/$slug': {
      id: '/about_/$slug'
      path: '/about/$slug'
      fullPath: '/about/$slug'
      preLoaderRoute: typeof AboutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/boletim': {
      id: '/admin/boletim'
      path: '/admin/boletim'
      fullPath: '/admin/boletim'
      preLoaderRoute: typeof AdminBoletimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/brasil': {
      id: '/admin/brasil'
      path: '/admin/brasil'
      fullPath: '/admin/brasil'
      preLoaderRoute: typeof AdminBrasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/consultores': {
      id: '/admin/consultores'
      path: '/admin/consultores'
      fullPath: '/admin/consultores'
      preLoaderRoute: typeof AdminConsultoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contrato': {
      id: '/admin/contrato'
      path: '/admin/contrato'
      fullPath: '/admin/contrato'
      preLoaderRoute: typeof AdminContratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresa': {
      id: '/admin/empresa'
      path: '/admin/empresa'
      fullPath: '/admin/empresa'
      preLoaderRoute: typeof AdminEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/admin/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/historico': {
      id: '/admin/historico'
      path: '/admin/historico'
      fullPath: '/admin/historico'
      preLoaderRoute: typeof AdminHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/indicadores': {
      id: '/admin/indicadores'
      path: '/admin/indicadores'
      fullPath: '/admin/indicadores'
      preLoaderRoute: typeof AdminIndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/admin/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/texts': {
      id: '/admin/texts'
      path: '/admin/texts'
      fullPath: '/admin/texts'
      preLoaderRoute: typeof AdminTextsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/admin/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boletim/cancelar': {
      id: '/boletim/cancelar'
      path: '/boletim/cancelar'
      fullPath: '/boletim/cancelar'
      preLoaderRoute: typeof BoletimCancelarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brasil_/$slug': {
      id: '/brasil_/$slug'
      path: '/brasil/$slug'
      fullPath: '/brasil/$slug'
      preLoaderRoute: typeof BrasilSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$slug': {
      id: '/content/$slug'
      path: '/$slug'
      fullPath: '/content/$slug'
      preLoaderRoute: typeof ContentSlugRouteImport
      parentRoute: typeof ContentRoute
    }
    '/newsletter/unsubscribe': {
      id: '/newsletter/unsubscribe'
      path: '/newsletter/unsubscribe'
      fullPath: '/newsletter/unsubscribe'
      preLoaderRoute: typeof NewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bulletin-weekly': {
      id: '/api/public/bulletin-weekly'
      path: '/api/public/bulletin-weekly'
      fullPath: '/api/public/bulletin-weekly'
      preLoaderRoute: typeof ApiPublicBulletinWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter-weekly': {
      id: '/api/public/newsletter-weekly'
      path: '/api/public/newsletter-weekly'
      fullPath: '/api/public/newsletter-weekly'
      preLoaderRoute: typeof ApiPublicNewsletterWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContentRouteChildren {
  ContentSlugRoute: typeof ContentSlugRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentSlugRoute: ContentSlugRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrasilRoute: BrasilRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ContentRoute: ContentRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AboutSlugRoute: AboutSlugRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminBoletimRoute: AdminBoletimRoute,
  AdminBrasilRoute: AdminBrasilRoute,
  AdminConsultoresRoute: AdminConsultoresRoute,
  AdminContentRoute: AdminContentRoute,
  AdminContratoRoute: AdminContratoRoute,
  AdminEmpresaRoute: AdminEmpresaRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminHistoricoRoute: AdminHistoricoRoute,
  AdminIndicadoresRoute: AdminIndicadoresRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTextsRoute: AdminTextsRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminUsersRoute: AdminUsersRoute,
  BoletimCancelarRoute: BoletimCancelarRoute,
  BrasilSlugRoute: BrasilSlugRoute,
  NewsletterUnsubscribeRoute: NewsletterUnsubscribeRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiPublicBulletinWeeklyRoute: ApiPublicBulletinWeeklyRoute,
  ApiPublicNewsletterWeeklyRoute: ApiPublicNewsletterWeeklyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
